### ISSUE TITLE
Logs are Bounced from TFC Log Piles

### ISSUE THREAD

**Issue by Exsolutus** [DoubleDoorDevelopment/OversizedItemInStorageArea#1]
With default configs, the addon will bounce logs out of TFC log piles. User can fix by adding log piles to the config blacklist, but it is best this is fixed by default.

**Comment by Claycorp** [comment]
Fixed with 3648290edf1e7c28a423f9ca9fa1311617b1bc07
The config changed to allow this so make sure to update the new one!
