### ISSUE TITLE
Error with AdventurePack Mining Helmet

### ISSUE THREAD

**Issue by liquidblur** [DoubleDoorDevelopment/OversizedItemInStorageArea#2]
https://paste.dimdev.org/uvodahiseq.mccrash

**Comment by Claycorp** [comment]
I'm not exactly sure what could have triggered it as the line number points to a `}` so I'm assuming it's a slot issue. If you can repeat it still feel free to drop a full log instead of the crash. Otherwise try with the new version and ban the container. That should fix the problem.

Thanks!

**Comment by Claycorp** [comment]
There's been no feed back on this it's assumed fixed/not an issues any longer.
