### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by TheNimbleNinja** [DoubleDoorDevelopment/OversizedItemInStorageArea#6]
when putting items into thermalbags that get kicked out of normal inventory when closed drops all the items but when you open it again they are still in it so its duping the items.

**Comment by Claycorp** [comment]
I found the issue. Seems like the inventory is written to disk before the close event is finished thus the item is saved in NBT even though the item isn't actively in the inventory any longer. This makes it appear again as that NBT is then read again when opening the bag.

There will be a fix for it soon. I need to do more testing beforehand though.

**Comment by TheNimbleNinja** [comment]
this might be a bug for all backpack mods

**Comment by Claycorp** [comment]
Fixed with 1.2
